/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HeaderLayoutRouteImport } from './routes/_header-layout'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as OgIndexRouteImport } from './routes/og.index'
import { Route as HeaderLayoutIndexRouteImport } from './routes/_header-layout.index'
import { Route as XrpcNsidRouteImport } from './routes/xrpc.$nsid'
import { Route as OgTagRouteImport } from './routes/og.tag'
import { Route as OgReviewRouteImport } from './routes/og.review'
import { Route as OgProfileRouteImport } from './routes/og.profile'
import { Route as HeaderLayoutSearchRouteImport } from './routes/_header-layout.search'
import { Route as HeaderLayoutNotificationsRouteImport } from './routes/_header-layout.notifications'
import { Route as HeaderLayoutAdminLayoutRouteImport } from './routes/_header-layout._admin-layout'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as HeaderLayoutProfileActorRouteImport } from './routes/_header-layout.profile.$actor'
import { Route as HeaderLayoutProductsManageRouteImport } from './routes/_header-layout.products.manage'
import { Route as HeaderLayoutProductsCreateRouteImport } from './routes/_header-layout.products.create'
import { Route as HeaderLayoutProductClaimRouteImport } from './routes/_header-layout.product.claim'
import { Route as HeaderLayoutDevelopersAtprotoRouteImport } from './routes/_header-layout.developers.atproto'
import { Route as HeaderLayoutCategoriesCategoryIdRouteImport } from './routes/_header-layout.categories.$categoryId'
import { Route as HeaderLayoutAppsTagsRouteImport } from './routes/_header-layout.apps.tags'
import { Route as HeaderLayoutAppsAllRouteImport } from './routes/_header-layout.apps.all'
import { Route as HeaderLayoutAppsTagRouteImport } from './routes/_header-layout.apps.$tag'
import { Route as HeaderLayoutProductsProductIdIndexRouteImport } from './routes/_header-layout.products.$productId.index'
import { Route as HeaderLayoutEcosystemsAppIndexRouteImport } from './routes/_header-layout.ecosystems.$app.index'
import { Route as HeaderLayoutAdminLayoutAdminIndexRouteImport } from './routes/_header-layout._admin-layout.admin.index'
import { Route as ApiAuthAtprotoSignupRouteImport } from './routes/api.auth.atproto.signup'
import { Route as ApiAuthAtprotoMetadataDotjsonRouteImport } from './routes/api.auth.atproto.metadata[.]json'
import { Route as ApiAuthAtprotoJwksDotjsonRouteImport } from './routes/api.auth.atproto.jwks[.]json'
import { Route as ApiAuthAtprotoCallbackRouteImport } from './routes/api.auth.atproto.callback'
import { Route as ApiAuthAtprotoAuthorizeRouteImport } from './routes/api.auth.atproto.authorize'
import { Route as HeaderLayoutProductsProductIdReviewsRouteImport } from './routes/_header-layout.products.$productId.reviews'
import { Route as HeaderLayoutProductsProductIdMentionsRouteImport } from './routes/_header-layout.products.$productId.mentions'
import { Route as HeaderLayoutProductsProductIdEditRouteImport } from './routes/_header-layout.products.$productId.edit'
import { Route as HeaderLayoutEcosystemsAppAllRouteImport } from './routes/_header-layout.ecosystems.$app.all'
import { Route as HeaderLayoutAdminLayoutAdminUnverifiedListingsRouteImport } from './routes/_header-layout._admin-layout.admin.unverified-listings'
import { Route as HeaderLayoutAdminLayoutAdminReviewsRouteImport } from './routes/_header-layout._admin-layout.admin.reviews'
import { Route as HeaderLayoutAdminLayoutAdminRecentlyClaimedRouteImport } from './routes/_header-layout._admin-layout.admin.recently-claimed'
import { Route as HeaderLayoutAdminLayoutAdminPendingClaimsRouteImport } from './routes/_header-layout._admin-layout.admin.pending-claims'
import { Route as HeaderLayoutAdminLayoutAdminManagedListingsRouteImport } from './routes/_header-layout._admin-layout.admin.managed-listings'
import { Route as HeaderLayoutAdminLayoutAdminHomePageHeroRouteImport } from './routes/_header-layout._admin-layout.admin.home-page-hero'
import { Route as HeaderLayoutAdminLayoutAdminAdminsRouteImport } from './routes/_header-layout._admin-layout.admin.admins'
import { Route as HeaderLayoutAdminLayoutAdminAddListingRouteImport } from './routes/_header-layout._admin-layout.admin.add-listing'
import { Route as HeaderLayoutProductsProductIdReviewsIndexRouteImport } from './routes/_header-layout.products.$productId.reviews.index'
import { Route as HeaderLayoutProductsProductIdReviewsWriteRouteImport } from './routes/_header-layout.products.$productId.reviews.write'
import { Route as HeaderLayoutProductsProductIdReviewsReviewIdEditRouteImport } from './routes/_header-layout.products.$productId.reviews.$reviewId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutRoute = HeaderLayoutRouteImport.update({
  id: '/_header-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const OgIndexRoute = OgIndexRouteImport.update({
  id: '/og/',
  path: '/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutIndexRoute = HeaderLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const XrpcNsidRoute = XrpcNsidRouteImport.update({
  id: '/xrpc/$nsid',
  path: '/xrpc/$nsid',
  getParentRoute: () => rootRouteImport,
} as any)
const OgTagRoute = OgTagRouteImport.update({
  id: '/og/tag',
  path: '/og/tag',
  getParentRoute: () => rootRouteImport,
} as any)
const OgReviewRoute = OgReviewRouteImport.update({
  id: '/og/review',
  path: '/og/review',
  getParentRoute: () => rootRouteImport,
} as any)
const OgProfileRoute = OgProfileRouteImport.update({
  id: '/og/profile',
  path: '/og/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutSearchRoute = HeaderLayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutNotificationsRoute =
  HeaderLayoutNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutRoute = HeaderLayoutAdminLayoutRouteImport.update({
  id: '/_admin-layout',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const HeaderLayoutProfileActorRoute =
  HeaderLayoutProfileActorRouteImport.update({
    id: '/profile/$actor',
    path: '/profile/$actor',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProductsManageRoute =
  HeaderLayoutProductsManageRouteImport.update({
    id: '/products/manage',
    path: '/products/manage',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProductsCreateRoute =
  HeaderLayoutProductsCreateRouteImport.update({
    id: '/products/create',
    path: '/products/create',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProductClaimRoute =
  HeaderLayoutProductClaimRouteImport.update({
    id: '/product/claim',
    path: '/product/claim',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutDevelopersAtprotoRoute =
  HeaderLayoutDevelopersAtprotoRouteImport.update({
    id: '/developers/atproto',
    path: '/developers/atproto',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutCategoriesCategoryIdRoute =
  HeaderLayoutCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutAppsTagsRoute = HeaderLayoutAppsTagsRouteImport.update({
  id: '/apps/tags',
  path: '/apps/tags',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutAppsAllRoute = HeaderLayoutAppsAllRouteImport.update({
  id: '/apps/all',
  path: '/apps/all',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutAppsTagRoute = HeaderLayoutAppsTagRouteImport.update({
  id: '/apps/$tag',
  path: '/apps/$tag',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutProductsProductIdIndexRoute =
  HeaderLayoutProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutEcosystemsAppIndexRoute =
  HeaderLayoutEcosystemsAppIndexRouteImport.update({
    id: '/ecosystems/$app/',
    path: '/ecosystems/$app/',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminIndexRoute =
  HeaderLayoutAdminLayoutAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const ApiAuthAtprotoSignupRoute = ApiAuthAtprotoSignupRouteImport.update({
  id: '/api/auth/atproto/signup',
  path: '/api/auth/atproto/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoMetadataDotjsonRoute =
  ApiAuthAtprotoMetadataDotjsonRouteImport.update({
    id: '/api/auth/atproto/metadata.json',
    path: '/api/auth/atproto/metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoJwksDotjsonRoute =
  ApiAuthAtprotoJwksDotjsonRouteImport.update({
    id: '/api/auth/atproto/jwks.json',
    path: '/api/auth/atproto/jwks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoCallbackRoute = ApiAuthAtprotoCallbackRouteImport.update({
  id: '/api/auth/atproto/callback',
  path: '/api/auth/atproto/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoAuthorizeRoute = ApiAuthAtprotoAuthorizeRouteImport.update({
  id: '/api/auth/atproto/authorize',
  path: '/api/auth/atproto/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutProductsProductIdReviewsRoute =
  HeaderLayoutProductsProductIdReviewsRouteImport.update({
    id: '/products/$productId/reviews',
    path: '/products/$productId/reviews',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProductsProductIdMentionsRoute =
  HeaderLayoutProductsProductIdMentionsRouteImport.update({
    id: '/products/$productId/mentions',
    path: '/products/$productId/mentions',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutProductsProductIdEditRoute =
  HeaderLayoutProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutEcosystemsAppAllRoute =
  HeaderLayoutEcosystemsAppAllRouteImport.update({
    id: '/ecosystems/$app/all',
    path: '/ecosystems/$app/all',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute =
  HeaderLayoutAdminLayoutAdminUnverifiedListingsRouteImport.update({
    id: '/admin/unverified-listings',
    path: '/admin/unverified-listings',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminReviewsRoute =
  HeaderLayoutAdminLayoutAdminReviewsRouteImport.update({
    id: '/admin/reviews',
    path: '/admin/reviews',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminRecentlyClaimedRoute =
  HeaderLayoutAdminLayoutAdminRecentlyClaimedRouteImport.update({
    id: '/admin/recently-claimed',
    path: '/admin/recently-claimed',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminPendingClaimsRoute =
  HeaderLayoutAdminLayoutAdminPendingClaimsRouteImport.update({
    id: '/admin/pending-claims',
    path: '/admin/pending-claims',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminManagedListingsRoute =
  HeaderLayoutAdminLayoutAdminManagedListingsRouteImport.update({
    id: '/admin/managed-listings',
    path: '/admin/managed-listings',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminHomePageHeroRoute =
  HeaderLayoutAdminLayoutAdminHomePageHeroRouteImport.update({
    id: '/admin/home-page-hero',
    path: '/admin/home-page-hero',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminAdminsRoute =
  HeaderLayoutAdminLayoutAdminAdminsRouteImport.update({
    id: '/admin/admins',
    path: '/admin/admins',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutAdminLayoutAdminAddListingRoute =
  HeaderLayoutAdminLayoutAdminAddListingRouteImport.update({
    id: '/admin/add-listing',
    path: '/admin/add-listing',
    getParentRoute: () => HeaderLayoutAdminLayoutRoute,
  } as any)
const HeaderLayoutProductsProductIdReviewsIndexRoute =
  HeaderLayoutProductsProductIdReviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HeaderLayoutProductsProductIdReviewsRoute,
  } as any)
const HeaderLayoutProductsProductIdReviewsWriteRoute =
  HeaderLayoutProductsProductIdReviewsWriteRouteImport.update({
    id: '/write',
    path: '/write',
    getParentRoute: () => HeaderLayoutProductsProductIdReviewsRoute,
  } as any)
const HeaderLayoutProductsProductIdReviewsReviewIdEditRoute =
  HeaderLayoutProductsProductIdReviewsReviewIdEditRouteImport.update({
    id: '/$reviewId/edit',
    path: '/$reviewId/edit',
    getParentRoute: () => HeaderLayoutProductsProductIdReviewsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$locale': typeof LocaleRouteWithChildren
  '/': typeof HeaderLayoutIndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/notifications': typeof HeaderLayoutNotificationsRoute
  '/search': typeof HeaderLayoutSearchRoute
  '/og/profile': typeof OgProfileRoute
  '/og/review': typeof OgReviewRoute
  '/og/tag': typeof OgTagRoute
  '/xrpc/$nsid': typeof XrpcNsidRoute
  '/og/': typeof OgIndexRoute
  '/apps/$tag': typeof HeaderLayoutAppsTagRoute
  '/apps/all': typeof HeaderLayoutAppsAllRoute
  '/apps/tags': typeof HeaderLayoutAppsTagsRoute
  '/categories/$categoryId': typeof HeaderLayoutCategoriesCategoryIdRoute
  '/developers/atproto': typeof HeaderLayoutDevelopersAtprotoRoute
  '/product/claim': typeof HeaderLayoutProductClaimRoute
  '/products/create': typeof HeaderLayoutProductsCreateRoute
  '/products/manage': typeof HeaderLayoutProductsManageRoute
  '/profile/$actor': typeof HeaderLayoutProfileActorRoute
  '/admin/add-listing': typeof HeaderLayoutAdminLayoutAdminAddListingRoute
  '/admin/admins': typeof HeaderLayoutAdminLayoutAdminAdminsRoute
  '/admin/home-page-hero': typeof HeaderLayoutAdminLayoutAdminHomePageHeroRoute
  '/admin/managed-listings': typeof HeaderLayoutAdminLayoutAdminManagedListingsRoute
  '/admin/pending-claims': typeof HeaderLayoutAdminLayoutAdminPendingClaimsRoute
  '/admin/recently-claimed': typeof HeaderLayoutAdminLayoutAdminRecentlyClaimedRoute
  '/admin/reviews': typeof HeaderLayoutAdminLayoutAdminReviewsRoute
  '/admin/unverified-listings': typeof HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute
  '/ecosystems/$app/all': typeof HeaderLayoutEcosystemsAppAllRoute
  '/products/$productId/edit': typeof HeaderLayoutProductsProductIdEditRoute
  '/products/$productId/mentions': typeof HeaderLayoutProductsProductIdMentionsRoute
  '/products/$productId/reviews': typeof HeaderLayoutProductsProductIdReviewsRouteWithChildren
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/admin/': typeof HeaderLayoutAdminLayoutAdminIndexRoute
  '/ecosystems/$app/': typeof HeaderLayoutEcosystemsAppIndexRoute
  '/products/$productId/': typeof HeaderLayoutProductsProductIdIndexRoute
  '/products/$productId/reviews/write': typeof HeaderLayoutProductsProductIdReviewsWriteRoute
  '/products/$productId/reviews/': typeof HeaderLayoutProductsProductIdReviewsIndexRoute
  '/products/$productId/reviews/$reviewId/edit': typeof HeaderLayoutProductsProductIdReviewsReviewIdEditRoute
}
export interface FileRoutesByTo {
  '/$locale': typeof LocaleRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/': typeof HeaderLayoutIndexRoute
  '/notifications': typeof HeaderLayoutNotificationsRoute
  '/search': typeof HeaderLayoutSearchRoute
  '/og/profile': typeof OgProfileRoute
  '/og/review': typeof OgReviewRoute
  '/og/tag': typeof OgTagRoute
  '/xrpc/$nsid': typeof XrpcNsidRoute
  '/og': typeof OgIndexRoute
  '/apps/$tag': typeof HeaderLayoutAppsTagRoute
  '/apps/all': typeof HeaderLayoutAppsAllRoute
  '/apps/tags': typeof HeaderLayoutAppsTagsRoute
  '/categories/$categoryId': typeof HeaderLayoutCategoriesCategoryIdRoute
  '/developers/atproto': typeof HeaderLayoutDevelopersAtprotoRoute
  '/product/claim': typeof HeaderLayoutProductClaimRoute
  '/products/create': typeof HeaderLayoutProductsCreateRoute
  '/products/manage': typeof HeaderLayoutProductsManageRoute
  '/profile/$actor': typeof HeaderLayoutProfileActorRoute
  '/admin/add-listing': typeof HeaderLayoutAdminLayoutAdminAddListingRoute
  '/admin/admins': typeof HeaderLayoutAdminLayoutAdminAdminsRoute
  '/admin/home-page-hero': typeof HeaderLayoutAdminLayoutAdminHomePageHeroRoute
  '/admin/managed-listings': typeof HeaderLayoutAdminLayoutAdminManagedListingsRoute
  '/admin/pending-claims': typeof HeaderLayoutAdminLayoutAdminPendingClaimsRoute
  '/admin/recently-claimed': typeof HeaderLayoutAdminLayoutAdminRecentlyClaimedRoute
  '/admin/reviews': typeof HeaderLayoutAdminLayoutAdminReviewsRoute
  '/admin/unverified-listings': typeof HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute
  '/ecosystems/$app/all': typeof HeaderLayoutEcosystemsAppAllRoute
  '/products/$productId/edit': typeof HeaderLayoutProductsProductIdEditRoute
  '/products/$productId/mentions': typeof HeaderLayoutProductsProductIdMentionsRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/admin': typeof HeaderLayoutAdminLayoutAdminIndexRoute
  '/ecosystems/$app': typeof HeaderLayoutEcosystemsAppIndexRoute
  '/products/$productId': typeof HeaderLayoutProductsProductIdIndexRoute
  '/products/$productId/reviews/write': typeof HeaderLayoutProductsProductIdReviewsWriteRoute
  '/products/$productId/reviews': typeof HeaderLayoutProductsProductIdReviewsIndexRoute
  '/products/$productId/reviews/$reviewId/edit': typeof HeaderLayoutProductsProductIdReviewsReviewIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$locale': typeof LocaleRouteWithChildren
  '/_header-layout': typeof HeaderLayoutRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/_header-layout/_admin-layout': typeof HeaderLayoutAdminLayoutRouteWithChildren
  '/_header-layout/notifications': typeof HeaderLayoutNotificationsRoute
  '/_header-layout/search': typeof HeaderLayoutSearchRoute
  '/og/profile': typeof OgProfileRoute
  '/og/review': typeof OgReviewRoute
  '/og/tag': typeof OgTagRoute
  '/xrpc/$nsid': typeof XrpcNsidRoute
  '/_header-layout/': typeof HeaderLayoutIndexRoute
  '/og/': typeof OgIndexRoute
  '/_header-layout/apps/$tag': typeof HeaderLayoutAppsTagRoute
  '/_header-layout/apps/all': typeof HeaderLayoutAppsAllRoute
  '/_header-layout/apps/tags': typeof HeaderLayoutAppsTagsRoute
  '/_header-layout/categories/$categoryId': typeof HeaderLayoutCategoriesCategoryIdRoute
  '/_header-layout/developers/atproto': typeof HeaderLayoutDevelopersAtprotoRoute
  '/_header-layout/product/claim': typeof HeaderLayoutProductClaimRoute
  '/_header-layout/products/create': typeof HeaderLayoutProductsCreateRoute
  '/_header-layout/products/manage': typeof HeaderLayoutProductsManageRoute
  '/_header-layout/profile/$actor': typeof HeaderLayoutProfileActorRoute
  '/_header-layout/_admin-layout/admin/add-listing': typeof HeaderLayoutAdminLayoutAdminAddListingRoute
  '/_header-layout/_admin-layout/admin/admins': typeof HeaderLayoutAdminLayoutAdminAdminsRoute
  '/_header-layout/_admin-layout/admin/home-page-hero': typeof HeaderLayoutAdminLayoutAdminHomePageHeroRoute
  '/_header-layout/_admin-layout/admin/managed-listings': typeof HeaderLayoutAdminLayoutAdminManagedListingsRoute
  '/_header-layout/_admin-layout/admin/pending-claims': typeof HeaderLayoutAdminLayoutAdminPendingClaimsRoute
  '/_header-layout/_admin-layout/admin/recently-claimed': typeof HeaderLayoutAdminLayoutAdminRecentlyClaimedRoute
  '/_header-layout/_admin-layout/admin/reviews': typeof HeaderLayoutAdminLayoutAdminReviewsRoute
  '/_header-layout/_admin-layout/admin/unverified-listings': typeof HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute
  '/_header-layout/ecosystems/$app/all': typeof HeaderLayoutEcosystemsAppAllRoute
  '/_header-layout/products/$productId/edit': typeof HeaderLayoutProductsProductIdEditRoute
  '/_header-layout/products/$productId/mentions': typeof HeaderLayoutProductsProductIdMentionsRoute
  '/_header-layout/products/$productId/reviews': typeof HeaderLayoutProductsProductIdReviewsRouteWithChildren
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/_header-layout/_admin-layout/admin/': typeof HeaderLayoutAdminLayoutAdminIndexRoute
  '/_header-layout/ecosystems/$app/': typeof HeaderLayoutEcosystemsAppIndexRoute
  '/_header-layout/products/$productId/': typeof HeaderLayoutProductsProductIdIndexRoute
  '/_header-layout/products/$productId/reviews/write': typeof HeaderLayoutProductsProductIdReviewsWriteRoute
  '/_header-layout/products/$productId/reviews/': typeof HeaderLayoutProductsProductIdReviewsIndexRoute
  '/_header-layout/products/$productId/reviews/$reviewId/edit': typeof HeaderLayoutProductsProductIdReviewsReviewIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale'
    | '/'
    | '/home'
    | '/login'
    | '/$locale/about'
    | '/notifications'
    | '/search'
    | '/og/profile'
    | '/og/review'
    | '/og/tag'
    | '/xrpc/$nsid'
    | '/og/'
    | '/apps/$tag'
    | '/apps/all'
    | '/apps/tags'
    | '/categories/$categoryId'
    | '/developers/atproto'
    | '/product/claim'
    | '/products/create'
    | '/products/manage'
    | '/profile/$actor'
    | '/admin/add-listing'
    | '/admin/admins'
    | '/admin/home-page-hero'
    | '/admin/managed-listings'
    | '/admin/pending-claims'
    | '/admin/recently-claimed'
    | '/admin/reviews'
    | '/admin/unverified-listings'
    | '/ecosystems/$app/all'
    | '/products/$productId/edit'
    | '/products/$productId/mentions'
    | '/products/$productId/reviews'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/admin/'
    | '/ecosystems/$app/'
    | '/products/$productId/'
    | '/products/$productId/reviews/write'
    | '/products/$productId/reviews/'
    | '/products/$productId/reviews/$reviewId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$locale'
    | '/home'
    | '/login'
    | '/$locale/about'
    | '/'
    | '/notifications'
    | '/search'
    | '/og/profile'
    | '/og/review'
    | '/og/tag'
    | '/xrpc/$nsid'
    | '/og'
    | '/apps/$tag'
    | '/apps/all'
    | '/apps/tags'
    | '/categories/$categoryId'
    | '/developers/atproto'
    | '/product/claim'
    | '/products/create'
    | '/products/manage'
    | '/profile/$actor'
    | '/admin/add-listing'
    | '/admin/admins'
    | '/admin/home-page-hero'
    | '/admin/managed-listings'
    | '/admin/pending-claims'
    | '/admin/recently-claimed'
    | '/admin/reviews'
    | '/admin/unverified-listings'
    | '/ecosystems/$app/all'
    | '/products/$productId/edit'
    | '/products/$productId/mentions'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/admin'
    | '/ecosystems/$app'
    | '/products/$productId'
    | '/products/$productId/reviews/write'
    | '/products/$productId/reviews'
    | '/products/$productId/reviews/$reviewId/edit'
  id:
    | '__root__'
    | '/$locale'
    | '/_header-layout'
    | '/home'
    | '/login'
    | '/$locale/about'
    | '/_header-layout/_admin-layout'
    | '/_header-layout/notifications'
    | '/_header-layout/search'
    | '/og/profile'
    | '/og/review'
    | '/og/tag'
    | '/xrpc/$nsid'
    | '/_header-layout/'
    | '/og/'
    | '/_header-layout/apps/$tag'
    | '/_header-layout/apps/all'
    | '/_header-layout/apps/tags'
    | '/_header-layout/categories/$categoryId'
    | '/_header-layout/developers/atproto'
    | '/_header-layout/product/claim'
    | '/_header-layout/products/create'
    | '/_header-layout/products/manage'
    | '/_header-layout/profile/$actor'
    | '/_header-layout/_admin-layout/admin/add-listing'
    | '/_header-layout/_admin-layout/admin/admins'
    | '/_header-layout/_admin-layout/admin/home-page-hero'
    | '/_header-layout/_admin-layout/admin/managed-listings'
    | '/_header-layout/_admin-layout/admin/pending-claims'
    | '/_header-layout/_admin-layout/admin/recently-claimed'
    | '/_header-layout/_admin-layout/admin/reviews'
    | '/_header-layout/_admin-layout/admin/unverified-listings'
    | '/_header-layout/ecosystems/$app/all'
    | '/_header-layout/products/$productId/edit'
    | '/_header-layout/products/$productId/mentions'
    | '/_header-layout/products/$productId/reviews'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/_header-layout/_admin-layout/admin/'
    | '/_header-layout/ecosystems/$app/'
    | '/_header-layout/products/$productId/'
    | '/_header-layout/products/$productId/reviews/write'
    | '/_header-layout/products/$productId/reviews/'
    | '/_header-layout/products/$productId/reviews/$reviewId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocaleRoute: typeof LocaleRouteWithChildren
  HeaderLayoutRoute: typeof HeaderLayoutRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OgProfileRoute: typeof OgProfileRoute
  OgReviewRoute: typeof OgReviewRoute
  OgTagRoute: typeof OgTagRoute
  XrpcNsidRoute: typeof XrpcNsidRoute
  OgIndexRoute: typeof OgIndexRoute
  ApiAuthAtprotoAuthorizeRoute: typeof ApiAuthAtprotoAuthorizeRoute
  ApiAuthAtprotoCallbackRoute: typeof ApiAuthAtprotoCallbackRoute
  ApiAuthAtprotoJwksDotjsonRoute: typeof ApiAuthAtprotoJwksDotjsonRoute
  ApiAuthAtprotoMetadataDotjsonRoute: typeof ApiAuthAtprotoMetadataDotjsonRoute
  ApiAuthAtprotoSignupRoute: typeof ApiAuthAtprotoSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout': {
      id: '/_header-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/': {
      id: '/og/'
      path: '/og'
      fullPath: '/og/'
      preLoaderRoute: typeof OgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/': {
      id: '/_header-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutIndexRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/xrpc/$nsid': {
      id: '/xrpc/$nsid'
      path: '/xrpc/$nsid'
      fullPath: '/xrpc/$nsid'
      preLoaderRoute: typeof XrpcNsidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/tag': {
      id: '/og/tag'
      path: '/og/tag'
      fullPath: '/og/tag'
      preLoaderRoute: typeof OgTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/review': {
      id: '/og/review'
      path: '/og/review'
      fullPath: '/og/review'
      preLoaderRoute: typeof OgReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/profile': {
      id: '/og/profile'
      path: '/og/profile'
      fullPath: '/og/profile'
      preLoaderRoute: typeof OgProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/search': {
      id: '/_header-layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof HeaderLayoutSearchRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/notifications': {
      id: '/_header-layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof HeaderLayoutNotificationsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/_admin-layout': {
      id: '/_header-layout/_admin-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/_header-layout/profile/$actor': {
      id: '/_header-layout/profile/$actor'
      path: '/profile/$actor'
      fullPath: '/profile/$actor'
      preLoaderRoute: typeof HeaderLayoutProfileActorRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/products/manage': {
      id: '/_header-layout/products/manage'
      path: '/products/manage'
      fullPath: '/products/manage'
      preLoaderRoute: typeof HeaderLayoutProductsManageRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/products/create': {
      id: '/_header-layout/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof HeaderLayoutProductsCreateRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/product/claim': {
      id: '/_header-layout/product/claim'
      path: '/product/claim'
      fullPath: '/product/claim'
      preLoaderRoute: typeof HeaderLayoutProductClaimRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/developers/atproto': {
      id: '/_header-layout/developers/atproto'
      path: '/developers/atproto'
      fullPath: '/developers/atproto'
      preLoaderRoute: typeof HeaderLayoutDevelopersAtprotoRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/categories/$categoryId': {
      id: '/_header-layout/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof HeaderLayoutCategoriesCategoryIdRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/apps/tags': {
      id: '/_header-layout/apps/tags'
      path: '/apps/tags'
      fullPath: '/apps/tags'
      preLoaderRoute: typeof HeaderLayoutAppsTagsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/apps/all': {
      id: '/_header-layout/apps/all'
      path: '/apps/all'
      fullPath: '/apps/all'
      preLoaderRoute: typeof HeaderLayoutAppsAllRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/apps/$tag': {
      id: '/_header-layout/apps/$tag'
      path: '/apps/$tag'
      fullPath: '/apps/$tag'
      preLoaderRoute: typeof HeaderLayoutAppsTagRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/products/$productId/': {
      id: '/_header-layout/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdIndexRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/ecosystems/$app/': {
      id: '/_header-layout/ecosystems/$app/'
      path: '/ecosystems/$app'
      fullPath: '/ecosystems/$app/'
      preLoaderRoute: typeof HeaderLayoutEcosystemsAppIndexRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/': {
      id: '/_header-layout/_admin-layout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminIndexRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/api/auth/atproto/signup': {
      id: '/api/auth/atproto/signup'
      path: '/api/auth/atproto/signup'
      fullPath: '/api/auth/atproto/signup'
      preLoaderRoute: typeof ApiAuthAtprotoSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/metadata.json': {
      id: '/api/auth/atproto/metadata.json'
      path: '/api/auth/atproto/metadata.json'
      fullPath: '/api/auth/atproto/metadata.json'
      preLoaderRoute: typeof ApiAuthAtprotoMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/jwks.json': {
      id: '/api/auth/atproto/jwks.json'
      path: '/api/auth/atproto/jwks.json'
      fullPath: '/api/auth/atproto/jwks.json'
      preLoaderRoute: typeof ApiAuthAtprotoJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/callback': {
      id: '/api/auth/atproto/callback'
      path: '/api/auth/atproto/callback'
      fullPath: '/api/auth/atproto/callback'
      preLoaderRoute: typeof ApiAuthAtprotoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/authorize': {
      id: '/api/auth/atproto/authorize'
      path: '/api/auth/atproto/authorize'
      fullPath: '/api/auth/atproto/authorize'
      preLoaderRoute: typeof ApiAuthAtprotoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/products/$productId/reviews': {
      id: '/_header-layout/products/$productId/reviews'
      path: '/products/$productId/reviews'
      fullPath: '/products/$productId/reviews'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdReviewsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/products/$productId/mentions': {
      id: '/_header-layout/products/$productId/mentions'
      path: '/products/$productId/mentions'
      fullPath: '/products/$productId/mentions'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdMentionsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/products/$productId/edit': {
      id: '/_header-layout/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdEditRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/ecosystems/$app/all': {
      id: '/_header-layout/ecosystems/$app/all'
      path: '/ecosystems/$app/all'
      fullPath: '/ecosystems/$app/all'
      preLoaderRoute: typeof HeaderLayoutEcosystemsAppAllRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/unverified-listings': {
      id: '/_header-layout/_admin-layout/admin/unverified-listings'
      path: '/admin/unverified-listings'
      fullPath: '/admin/unverified-listings'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminUnverifiedListingsRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/reviews': {
      id: '/_header-layout/_admin-layout/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminReviewsRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/recently-claimed': {
      id: '/_header-layout/_admin-layout/admin/recently-claimed'
      path: '/admin/recently-claimed'
      fullPath: '/admin/recently-claimed'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminRecentlyClaimedRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/pending-claims': {
      id: '/_header-layout/_admin-layout/admin/pending-claims'
      path: '/admin/pending-claims'
      fullPath: '/admin/pending-claims'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminPendingClaimsRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/managed-listings': {
      id: '/_header-layout/_admin-layout/admin/managed-listings'
      path: '/admin/managed-listings'
      fullPath: '/admin/managed-listings'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminManagedListingsRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/home-page-hero': {
      id: '/_header-layout/_admin-layout/admin/home-page-hero'
      path: '/admin/home-page-hero'
      fullPath: '/admin/home-page-hero'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminHomePageHeroRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/admins': {
      id: '/_header-layout/_admin-layout/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminAdminsRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/_admin-layout/admin/add-listing': {
      id: '/_header-layout/_admin-layout/admin/add-listing'
      path: '/admin/add-listing'
      fullPath: '/admin/add-listing'
      preLoaderRoute: typeof HeaderLayoutAdminLayoutAdminAddListingRouteImport
      parentRoute: typeof HeaderLayoutAdminLayoutRoute
    }
    '/_header-layout/products/$productId/reviews/': {
      id: '/_header-layout/products/$productId/reviews/'
      path: '/'
      fullPath: '/products/$productId/reviews/'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdReviewsIndexRouteImport
      parentRoute: typeof HeaderLayoutProductsProductIdReviewsRoute
    }
    '/_header-layout/products/$productId/reviews/write': {
      id: '/_header-layout/products/$productId/reviews/write'
      path: '/write'
      fullPath: '/products/$productId/reviews/write'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdReviewsWriteRouteImport
      parentRoute: typeof HeaderLayoutProductsProductIdReviewsRoute
    }
    '/_header-layout/products/$productId/reviews/$reviewId/edit': {
      id: '/_header-layout/products/$productId/reviews/$reviewId/edit'
      path: '/$reviewId/edit'
      fullPath: '/products/$productId/reviews/$reviewId/edit'
      preLoaderRoute: typeof HeaderLayoutProductsProductIdReviewsReviewIdEditRouteImport
      parentRoute: typeof HeaderLayoutProductsProductIdReviewsRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface HeaderLayoutAdminLayoutRouteChildren {
  HeaderLayoutAdminLayoutAdminAddListingRoute: typeof HeaderLayoutAdminLayoutAdminAddListingRoute
  HeaderLayoutAdminLayoutAdminAdminsRoute: typeof HeaderLayoutAdminLayoutAdminAdminsRoute
  HeaderLayoutAdminLayoutAdminHomePageHeroRoute: typeof HeaderLayoutAdminLayoutAdminHomePageHeroRoute
  HeaderLayoutAdminLayoutAdminManagedListingsRoute: typeof HeaderLayoutAdminLayoutAdminManagedListingsRoute
  HeaderLayoutAdminLayoutAdminPendingClaimsRoute: typeof HeaderLayoutAdminLayoutAdminPendingClaimsRoute
  HeaderLayoutAdminLayoutAdminRecentlyClaimedRoute: typeof HeaderLayoutAdminLayoutAdminRecentlyClaimedRoute
  HeaderLayoutAdminLayoutAdminReviewsRoute: typeof HeaderLayoutAdminLayoutAdminReviewsRoute
  HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute: typeof HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute
  HeaderLayoutAdminLayoutAdminIndexRoute: typeof HeaderLayoutAdminLayoutAdminIndexRoute
}

const HeaderLayoutAdminLayoutRouteChildren: HeaderLayoutAdminLayoutRouteChildren =
  {
    HeaderLayoutAdminLayoutAdminAddListingRoute:
      HeaderLayoutAdminLayoutAdminAddListingRoute,
    HeaderLayoutAdminLayoutAdminAdminsRoute:
      HeaderLayoutAdminLayoutAdminAdminsRoute,
    HeaderLayoutAdminLayoutAdminHomePageHeroRoute:
      HeaderLayoutAdminLayoutAdminHomePageHeroRoute,
    HeaderLayoutAdminLayoutAdminManagedListingsRoute:
      HeaderLayoutAdminLayoutAdminManagedListingsRoute,
    HeaderLayoutAdminLayoutAdminPendingClaimsRoute:
      HeaderLayoutAdminLayoutAdminPendingClaimsRoute,
    HeaderLayoutAdminLayoutAdminRecentlyClaimedRoute:
      HeaderLayoutAdminLayoutAdminRecentlyClaimedRoute,
    HeaderLayoutAdminLayoutAdminReviewsRoute:
      HeaderLayoutAdminLayoutAdminReviewsRoute,
    HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute:
      HeaderLayoutAdminLayoutAdminUnverifiedListingsRoute,
    HeaderLayoutAdminLayoutAdminIndexRoute:
      HeaderLayoutAdminLayoutAdminIndexRoute,
  }

const HeaderLayoutAdminLayoutRouteWithChildren =
  HeaderLayoutAdminLayoutRoute._addFileChildren(
    HeaderLayoutAdminLayoutRouteChildren,
  )

interface HeaderLayoutProductsProductIdReviewsRouteChildren {
  HeaderLayoutProductsProductIdReviewsWriteRoute: typeof HeaderLayoutProductsProductIdReviewsWriteRoute
  HeaderLayoutProductsProductIdReviewsIndexRoute: typeof HeaderLayoutProductsProductIdReviewsIndexRoute
  HeaderLayoutProductsProductIdReviewsReviewIdEditRoute: typeof HeaderLayoutProductsProductIdReviewsReviewIdEditRoute
}

const HeaderLayoutProductsProductIdReviewsRouteChildren: HeaderLayoutProductsProductIdReviewsRouteChildren =
  {
    HeaderLayoutProductsProductIdReviewsWriteRoute:
      HeaderLayoutProductsProductIdReviewsWriteRoute,
    HeaderLayoutProductsProductIdReviewsIndexRoute:
      HeaderLayoutProductsProductIdReviewsIndexRoute,
    HeaderLayoutProductsProductIdReviewsReviewIdEditRoute:
      HeaderLayoutProductsProductIdReviewsReviewIdEditRoute,
  }

const HeaderLayoutProductsProductIdReviewsRouteWithChildren =
  HeaderLayoutProductsProductIdReviewsRoute._addFileChildren(
    HeaderLayoutProductsProductIdReviewsRouteChildren,
  )

interface HeaderLayoutRouteChildren {
  HeaderLayoutAdminLayoutRoute: typeof HeaderLayoutAdminLayoutRouteWithChildren
  HeaderLayoutNotificationsRoute: typeof HeaderLayoutNotificationsRoute
  HeaderLayoutSearchRoute: typeof HeaderLayoutSearchRoute
  HeaderLayoutIndexRoute: typeof HeaderLayoutIndexRoute
  HeaderLayoutAppsTagRoute: typeof HeaderLayoutAppsTagRoute
  HeaderLayoutAppsAllRoute: typeof HeaderLayoutAppsAllRoute
  HeaderLayoutAppsTagsRoute: typeof HeaderLayoutAppsTagsRoute
  HeaderLayoutCategoriesCategoryIdRoute: typeof HeaderLayoutCategoriesCategoryIdRoute
  HeaderLayoutDevelopersAtprotoRoute: typeof HeaderLayoutDevelopersAtprotoRoute
  HeaderLayoutProductClaimRoute: typeof HeaderLayoutProductClaimRoute
  HeaderLayoutProductsCreateRoute: typeof HeaderLayoutProductsCreateRoute
  HeaderLayoutProductsManageRoute: typeof HeaderLayoutProductsManageRoute
  HeaderLayoutProfileActorRoute: typeof HeaderLayoutProfileActorRoute
  HeaderLayoutEcosystemsAppAllRoute: typeof HeaderLayoutEcosystemsAppAllRoute
  HeaderLayoutProductsProductIdEditRoute: typeof HeaderLayoutProductsProductIdEditRoute
  HeaderLayoutProductsProductIdMentionsRoute: typeof HeaderLayoutProductsProductIdMentionsRoute
  HeaderLayoutProductsProductIdReviewsRoute: typeof HeaderLayoutProductsProductIdReviewsRouteWithChildren
  HeaderLayoutEcosystemsAppIndexRoute: typeof HeaderLayoutEcosystemsAppIndexRoute
  HeaderLayoutProductsProductIdIndexRoute: typeof HeaderLayoutProductsProductIdIndexRoute
}

const HeaderLayoutRouteChildren: HeaderLayoutRouteChildren = {
  HeaderLayoutAdminLayoutRoute: HeaderLayoutAdminLayoutRouteWithChildren,
  HeaderLayoutNotificationsRoute: HeaderLayoutNotificationsRoute,
  HeaderLayoutSearchRoute: HeaderLayoutSearchRoute,
  HeaderLayoutIndexRoute: HeaderLayoutIndexRoute,
  HeaderLayoutAppsTagRoute: HeaderLayoutAppsTagRoute,
  HeaderLayoutAppsAllRoute: HeaderLayoutAppsAllRoute,
  HeaderLayoutAppsTagsRoute: HeaderLayoutAppsTagsRoute,
  HeaderLayoutCategoriesCategoryIdRoute: HeaderLayoutCategoriesCategoryIdRoute,
  HeaderLayoutDevelopersAtprotoRoute: HeaderLayoutDevelopersAtprotoRoute,
  HeaderLayoutProductClaimRoute: HeaderLayoutProductClaimRoute,
  HeaderLayoutProductsCreateRoute: HeaderLayoutProductsCreateRoute,
  HeaderLayoutProductsManageRoute: HeaderLayoutProductsManageRoute,
  HeaderLayoutProfileActorRoute: HeaderLayoutProfileActorRoute,
  HeaderLayoutEcosystemsAppAllRoute: HeaderLayoutEcosystemsAppAllRoute,
  HeaderLayoutProductsProductIdEditRoute:
    HeaderLayoutProductsProductIdEditRoute,
  HeaderLayoutProductsProductIdMentionsRoute:
    HeaderLayoutProductsProductIdMentionsRoute,
  HeaderLayoutProductsProductIdReviewsRoute:
    HeaderLayoutProductsProductIdReviewsRouteWithChildren,
  HeaderLayoutEcosystemsAppIndexRoute: HeaderLayoutEcosystemsAppIndexRoute,
  HeaderLayoutProductsProductIdIndexRoute:
    HeaderLayoutProductsProductIdIndexRoute,
}

const HeaderLayoutRouteWithChildren = HeaderLayoutRoute._addFileChildren(
  HeaderLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LocaleRoute: LocaleRouteWithChildren,
  HeaderLayoutRoute: HeaderLayoutRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OgProfileRoute: OgProfileRoute,
  OgReviewRoute: OgReviewRoute,
  OgTagRoute: OgTagRoute,
  XrpcNsidRoute: XrpcNsidRoute,
  OgIndexRoute: OgIndexRoute,
  ApiAuthAtprotoAuthorizeRoute: ApiAuthAtprotoAuthorizeRoute,
  ApiAuthAtprotoCallbackRoute: ApiAuthAtprotoCallbackRoute,
  ApiAuthAtprotoJwksDotjsonRoute: ApiAuthAtprotoJwksDotjsonRoute,
  ApiAuthAtprotoMetadataDotjsonRoute: ApiAuthAtprotoMetadataDotjsonRoute,
  ApiAuthAtprotoSignupRoute: ApiAuthAtprotoSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
